/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface HealthStatus {
  'status' : string,
  'totalPredictions' : bigint,
  'version' : string,
}
export interface HistoryRecord {
  'id' : bigint,
  'timeframe' : string,
  'timestamp' : bigint,
  'signal' : string,
  'predictedChangePercent' : number,
  'confidence' : number,
  'symbol' : string,
}
export interface PredictionResult {
  'rsi' : number,
  'sma' : number,
  'recentPrices' : Array<number>,
  'currentPrice' : number,
  'volatility' : number,
  'sentimentLabel' : string,
  'timeframe' : string,
  'sentimentScore' : number,
  'macd' : number,
  'momentum' : number,
  'signal' : string,
  'predictedChangePercent' : number,
  'confidence' : number,
  'symbol' : string,
}
export interface _SERVICE {
  'clearHistory' : ActorMethod<[], undefined>,
  'getHealth' : ActorMethod<[], HealthStatus>,
  'getPredictionHistory' : ActorMethod<[], Array<HistoryRecord>>,
  'getSupportedSymbols' : ActorMethod<[], Array<string>>,
  'predict' : ActorMethod<[string, string], PredictionResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];