/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const HealthStatus = IDL.Record({
  'status' : IDL.Text,
  'totalPredictions' : IDL.Nat,
  'version' : IDL.Text,
});
export const HistoryRecord = IDL.Record({
  'id' : IDL.Nat,
  'timeframe' : IDL.Text,
  'timestamp' : IDL.Int,
  'signal' : IDL.Text,
  'predictedChangePercent' : IDL.Float64,
  'confidence' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const PredictionResult = IDL.Record({
  'rsi' : IDL.Float64,
  'sma' : IDL.Float64,
  'recentPrices' : IDL.Vec(IDL.Float64),
  'currentPrice' : IDL.Float64,
  'volatility' : IDL.Float64,
  'sentimentLabel' : IDL.Text,
  'timeframe' : IDL.Text,
  'sentimentScore' : IDL.Float64,
  'macd' : IDL.Float64,
  'momentum' : IDL.Float64,
  'signal' : IDL.Text,
  'predictedChangePercent' : IDL.Float64,
  'confidence' : IDL.Float64,
  'symbol' : IDL.Text,
});

export const idlService = IDL.Service({
  'clearHistory' : IDL.Func([], [], []),
  'getHealth' : IDL.Func([], [HealthStatus], ['query']),
  'getPredictionHistory' : IDL.Func([], [IDL.Vec(HistoryRecord)], ['query']),
  'getSupportedSymbols' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'predict' : IDL.Func([IDL.Text, IDL.Text], [PredictionResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const HealthStatus = IDL.Record({
    'status' : IDL.Text,
    'totalPredictions' : IDL.Nat,
    'version' : IDL.Text,
  });
  const HistoryRecord = IDL.Record({
    'id' : IDL.Nat,
    'timeframe' : IDL.Text,
    'timestamp' : IDL.Int,
    'signal' : IDL.Text,
    'predictedChangePercent' : IDL.Float64,
    'confidence' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const PredictionResult = IDL.Record({
    'rsi' : IDL.Float64,
    'sma' : IDL.Float64,
    'recentPrices' : IDL.Vec(IDL.Float64),
    'currentPrice' : IDL.Float64,
    'volatility' : IDL.Float64,
    'sentimentLabel' : IDL.Text,
    'timeframe' : IDL.Text,
    'sentimentScore' : IDL.Float64,
    'macd' : IDL.Float64,
    'momentum' : IDL.Float64,
    'signal' : IDL.Text,
    'predictedChangePercent' : IDL.Float64,
    'confidence' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  
  return IDL.Service({
    'clearHistory' : IDL.Func([], [], []),
    'getHealth' : IDL.Func([], [HealthStatus], ['query']),
    'getPredictionHistory' : IDL.Func([], [IDL.Vec(HistoryRecord)], ['query']),
    'getSupportedSymbols' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'predict' : IDL.Func([IDL.Text, IDL.Text], [PredictionResult], []),
  });
};

export const init = ({ IDL }) => { return []; };