/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Indicators = IDL.Record({
  'ema' : IDL.Float64,
  'rsi' : IDL.Float64,
  'sma' : IDL.Float64,
  'volatility' : IDL.Float64,
  'macd' : IDL.Float64,
  'sentiment' : IDL.Float64,
  'momentum' : IDL.Float64,
});
export const PriceRecord = IDL.Record({
  'volume' : IDL.Float64,
  'timestamp' : IDL.Int,
  'price' : IDL.Float64,
});
export const Prediction = IDL.Record({
  'ema' : IDL.Float64,
  'rsi' : IDL.Float64,
  'sma' : IDL.Float64,
  'prediction' : IDL.Float64,
  'macd' : IDL.Float64,
  'signal' : IDL.Text,
  'confidence' : IDL.Float64,
});

export const idlService = IDL.Service({
  'getIndicators' : IDL.Func([IDL.Text], [Indicators], ['query']),
  'getPriceHistory' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(PriceRecord)],
      ['query'],
    ),
  'predict' : IDL.Func([IDL.Text, IDL.Text], [Prediction], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Indicators = IDL.Record({
    'ema' : IDL.Float64,
    'rsi' : IDL.Float64,
    'sma' : IDL.Float64,
    'volatility' : IDL.Float64,
    'macd' : IDL.Float64,
    'sentiment' : IDL.Float64,
    'momentum' : IDL.Float64,
  });
  const PriceRecord = IDL.Record({
    'volume' : IDL.Float64,
    'timestamp' : IDL.Int,
    'price' : IDL.Float64,
  });
  const Prediction = IDL.Record({
    'ema' : IDL.Float64,
    'rsi' : IDL.Float64,
    'sma' : IDL.Float64,
    'prediction' : IDL.Float64,
    'macd' : IDL.Float64,
    'signal' : IDL.Text,
    'confidence' : IDL.Float64,
  });
  
  return IDL.Service({
    'getIndicators' : IDL.Func([IDL.Text], [Indicators], ['query']),
    'getPriceHistory' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(PriceRecord)],
        ['query'],
      ),
    'predict' : IDL.Func([IDL.Text, IDL.Text], [Prediction], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };